export { default as CVHeader } from './CVHeader.astro'
export { default as Profile } from './Profile.astro'
export { default as Experience } from './Experience.astro'
export { default as Education } from './Education.astro'
export { default as Skills } from './Skills.astro'
export { default as Languages } from './Languages.astro'
